# Generated by Django 3.2.8 on 2021-12-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
